package com.example.model.entity;
import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.LocalDateTime;
import java.util.List;

@Entity
@Table(name = "document")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder

public class Document {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(unique = true, nullable = false)
    private String title;
    private String description;
    private Long version;
    private LocalDateTime date_created;




    @OneToMany(mappedBy = "document")
    @JsonManagedReference
    private List<Comment> comentariosHechos;

    @ManyToOne
    @JoinColumn(name = "repositorio_id")
    @JsonBackReference
    private Repository repositorio;

    @ManyToOne
    @JoinColumn(name = "usuario_id", nullable = false)
    private User usuario;

    public List<Comment> getComments() {
        return comentariosHechos;
    }

    // Constructors, getters, and setters can be generated by Lombok
}
